#pragma once

const int MODBUS_SEND_SLAVE_ADDRESS_POS = 0, MODBUS_SEND_FUNCTION_POS = 1, MODBUS_SEND_HOST_ADDRESS_POS = 2, MODBUS_SEND_COUNT_POS = 3;

const int MODBUS_RECV_HOST_ADDRESS_POS = 0, MODBUS_RECV_FUNCTION_POS = 1, MODBUS_RECV_SLAVE_ADDRESS_POS = 2, MODBUS_RECV_COUNT_POS = 3, MODBUS_RECV_DATA_POS = 4;

const int MODBUS_READ_CELL_DYNAMIC = 103;
const int MODBUS_READ_SYSTEM_DYNAMIC = 111;

